export type KeyCode =
    // Alphanumeric section
    | "KeyA"
    | "KeyB"
    | "KeyC"
    | "KeyD"
    | "KeyE"
    | "KeyF"
    | "KeyG"
    | "KeyH"
    | "KeyI"
    | "KeyJ"
    | "KeyK"
    | "KeyL"
    | "KeyM"
    | "KeyN"
    | "KeyO"
    | "KeyP"
    | "KeyQ"
    | "KeyR"
    | "KeyS"
    | "KeyT"
    | "KeyU"
    | "KeyV"
    | "KeyW"
    | "KeyX"
    | "KeyY"
    | "KeyZ"
    | "Digit0"
    | "Digit1"
    | "Digit2"
    | "Digit3"
    | "Digit4"
    | "Digit5"
    | "Digit6"
    | "Digit7"
    | "Digit8"
    | "Digit9"

    // Function keys
    | "F1"
    | "F2"
    | "F3"
    | "F4"
    | "F5"
    | "F6"
    | "F7"
    | "F8"
    | "F9"
    | "F10"
    | "F11"
    | "F12"
    | "F13"
    | "F14"
    | "F15"
    | "F16"
    | "F17"
    | "F18"
    | "F19"
    | "F20"
    | "F21"
    | "F22"
    | "F23"
    | "F24"

    // Control keys
    | "Enter"
    | "Escape"
    | "Backspace"
    | "Tab"
    | "Space"
    | "ShiftLeft"
    | "ShiftRight"
    | "ControlLeft"
    | "ControlRight"
    | "AltLeft"
    | "AltRight"
    | "MetaLeft"
    | "MetaRight"
    | "CapsLock"
    | "NumLock"
    | "ScrollLock"

    // Arrow keys
    | "ArrowUp"
    | "ArrowDown"
    | "ArrowLeft"
    | "ArrowRight"

    // Navigation
    | "Insert"
    | "Delete"
    | "Home"
    | "End"
    | "PageUp"
    | "PageDown"

    // Symbols and modifiers
    | "Minus"
    | "Equal"
    | "BracketLeft"
    | "BracketRight"
    | "Backslash"
    | "Semicolon"
    | "Quote"
    | "Backquote"
    | "Comma"
    | "Period"
    | "Slash"

    // Numpad section
    | "Numpad0"
    | "Numpad1"
    | "Numpad2"
    | "Numpad3"
    | "Numpad4"
    | "Numpad5"
    | "Numpad6"
    | "Numpad7"
    | "Numpad8"
    | "Numpad9"
    | "NumpadAdd"
    | "NumpadSubtract"
    | "NumpadMultiply"
    | "NumpadDivide"
    | "NumpadDecimal"
    | "NumpadEnter"
    | "NumpadEqual"
    | "NumpadComma"

    // Misc
    | "ContextMenu"
    | "PrintScreen"
    | "Pause"
    | "IntlBackslash"
    | "Lang1"
    | "Lang2"
    | "Convert"
    | "NonConvert"
    | "KanaMode"
    | "HangulMode"
    | "HanjaMode"
    | "Fn"
    | "FnLock"
    | "OSLeft"
    | "OSRight"
    | ""
