use std::{fs, path::Path};

use anyhow::Result;
use wtransport::Identity;

use crate::model::{CertificateHash, CertificateHashes};

/// `WebTransport` runs over QUIC, so the server always needs a TLS identity.
/// Loads the certificate and key from `cert_directory`, generating a self-signed
/// pair there if none is present.
pub async fn build_identity(cert_directory: &Path) -> Result<Identity> {
    ensure_certificate(cert_directory).await?;

    let identity = Identity::load_pemfiles(
        cert_directory.join("cert.pem"),
        cert_directory.join("key.pem"),
    )
    .await?;

    Ok(identity)
}

/// Writes a self-signed certificate and keypair to `path` if one isn't already present.
///
/// The certificate is valid for two weeks, which is the longest a browser will
/// accept for a certificate pinned with `serverCertificateHashes` — the only way
/// a browser will trust a self-signed `WebTransport` certificate at all. Once it
/// expires the pair has to be regenerated by deleting it.
async fn ensure_certificate(path: &Path) -> Result<()> {
    if !fs::exists(path)? {
        fs::create_dir_all(path)?;
    }

    if fs::exists(path.join("cert.pem"))? {
        return Ok(());
    }

    let identity = Identity::self_signed(["localhost", "127.0.0.1", "0.0.0.0", "::1"])?;

    identity
        .certificate_chain()
        .store_pemfile(path.join("cert.pem"))
        .await?;

    identity
        .private_key()
        .store_secret_pemfile(path.join("key.pem"))
        .await?;

    Ok(())
}

/// Browsers will not offer to trust a self-signed WebTransport certificate the
/// way they do for HTTPS, so clients pin these digests with
/// `serverCertificateHashes` instead. They are served over `GET /cert`
pub fn build_hashes(identity: &Identity) -> CertificateHashes {
    CertificateHashes {
        hashes: identity
            .certificate_chain()
            .as_slice()
            .iter()
            .map(|certificate| CertificateHash::sha256(certificate.hash().as_ref()))
            .collect(),
    }
}
