# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProtoRobot.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProtoRobot.proto',
  package='Synthesis.Simulator',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x10ProtoRobot.proto\x12\x13Synthesis.Simulator\"\xfb\x01\n\nProtoRobot\x12\x11\n\trobotName\x18\x01 \x01(\t\x12\x33\n\x08position\x18\x02 \x01(\x0b\x32!.Synthesis.Simulator.ProtoVector3\x12-\n\x05nodes\x18\x03 \x03(\x0b\x32\x1e.Synthesis.Simulator.ProtoNode\x12\x41\n\tdriveType\x18\x04 \x01(\x0e\x32..Synthesis.Simulator.ProtoRobot.DrivetrainType\"3\n\x0e\x44rivetrainType\x12\x08\n\x04Tank\x10\x00\x12\n\n\x06Swerve\x10\x01\x12\x0b\n\x07NoDrive\x10\x02\"N\n\nProtoField\x12\x11\n\tFieldName\x18\x01 \x01(\t\x12-\n\x05nodes\x18\x02 \x03(\x0b\x32\x1e.Synthesis.Simulator.ProtoNode\"\xfe\x01\n\tProtoNode\x12\x11\n\tisDynamic\x18\x01 \x01(\x08\x12\x0e\n\x06nodeID\x18\x02 \x01(\x05\x12\x12\n\nparentNode\x18\x03 \x01(\x05\x12\x0c\n\x04mass\x18\x04 \x01(\x02\x12\x37\n\x0c\x63\x65nterOfMass\x18\x05 \x01(\x0b\x32!.Synthesis.Simulator.ProtoVector3\x12\x33\n\x08position\x18\x06 \x01(\x0b\x32!.Synthesis.Simulator.ProtoVector3\x12\x30\n\x06\x62odies\x18\x07 \x03(\x0b\x32 .Synthesis.Simulator.ProtoObject\x12\x0c\n\x04name\x18\x08 \x01(\t\"\xb1\x01\n\x0bProtoObject\x12\x33\n\x08position\x18\x01 \x01(\x0b\x32!.Synthesis.Simulator.ProtoVector3\x12\x30\n\x05verts\x18\x02 \x03(\x0b\x32!.Synthesis.Simulator.ProtoVector3\x12\x0c\n\x04tris\x18\x03 \x03(\x05\x12-\n\x02uv\x18\x04 \x03(\x0b\x32!.Synthesis.Simulator.ProtoVector2\"/\n\x0cProtoVector3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"$\n\x0cProtoVector2\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x62\x06proto3'
)



_PROTOROBOT_DRIVETRAINTYPE = _descriptor.EnumDescriptor(
  name='DrivetrainType',
  full_name='Synthesis.Simulator.ProtoRobot.DrivetrainType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Tank', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Swerve', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NoDrive', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=242,
  serialized_end=293,
)
_sym_db.RegisterEnumDescriptor(_PROTOROBOT_DRIVETRAINTYPE)


_PROTOROBOT = _descriptor.Descriptor(
  name='ProtoRobot',
  full_name='Synthesis.Simulator.ProtoRobot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='robotName', full_name='Synthesis.Simulator.ProtoRobot.robotName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='Synthesis.Simulator.ProtoRobot.position', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='Synthesis.Simulator.ProtoRobot.nodes', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='driveType', full_name='Synthesis.Simulator.ProtoRobot.driveType', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PROTOROBOT_DRIVETRAINTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=293,
)


_PROTOFIELD = _descriptor.Descriptor(
  name='ProtoField',
  full_name='Synthesis.Simulator.ProtoField',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='FieldName', full_name='Synthesis.Simulator.ProtoField.FieldName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='Synthesis.Simulator.ProtoField.nodes', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=295,
  serialized_end=373,
)


_PROTONODE = _descriptor.Descriptor(
  name='ProtoNode',
  full_name='Synthesis.Simulator.ProtoNode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isDynamic', full_name='Synthesis.Simulator.ProtoNode.isDynamic', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nodeID', full_name='Synthesis.Simulator.ProtoNode.nodeID', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parentNode', full_name='Synthesis.Simulator.ProtoNode.parentNode', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mass', full_name='Synthesis.Simulator.ProtoNode.mass', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='centerOfMass', full_name='Synthesis.Simulator.ProtoNode.centerOfMass', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='Synthesis.Simulator.ProtoNode.position', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bodies', full_name='Synthesis.Simulator.ProtoNode.bodies', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='Synthesis.Simulator.ProtoNode.name', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=376,
  serialized_end=630,
)


_PROTOOBJECT = _descriptor.Descriptor(
  name='ProtoObject',
  full_name='Synthesis.Simulator.ProtoObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='Synthesis.Simulator.ProtoObject.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='verts', full_name='Synthesis.Simulator.ProtoObject.verts', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tris', full_name='Synthesis.Simulator.ProtoObject.tris', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uv', full_name='Synthesis.Simulator.ProtoObject.uv', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=633,
  serialized_end=810,
)


_PROTOVECTOR3 = _descriptor.Descriptor(
  name='ProtoVector3',
  full_name='Synthesis.Simulator.ProtoVector3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Synthesis.Simulator.ProtoVector3.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Synthesis.Simulator.ProtoVector3.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='Synthesis.Simulator.ProtoVector3.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=812,
  serialized_end=859,
)


_PROTOVECTOR2 = _descriptor.Descriptor(
  name='ProtoVector2',
  full_name='Synthesis.Simulator.ProtoVector2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Synthesis.Simulator.ProtoVector2.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Synthesis.Simulator.ProtoVector2.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=861,
  serialized_end=897,
)

_PROTOROBOT.fields_by_name['position'].message_type = _PROTOVECTOR3
_PROTOROBOT.fields_by_name['nodes'].message_type = _PROTONODE
_PROTOROBOT.fields_by_name['driveType'].enum_type = _PROTOROBOT_DRIVETRAINTYPE
_PROTOROBOT_DRIVETRAINTYPE.containing_type = _PROTOROBOT
_PROTOFIELD.fields_by_name['nodes'].message_type = _PROTONODE
_PROTONODE.fields_by_name['centerOfMass'].message_type = _PROTOVECTOR3
_PROTONODE.fields_by_name['position'].message_type = _PROTOVECTOR3
_PROTONODE.fields_by_name['bodies'].message_type = _PROTOOBJECT
_PROTOOBJECT.fields_by_name['position'].message_type = _PROTOVECTOR3
_PROTOOBJECT.fields_by_name['verts'].message_type = _PROTOVECTOR3
_PROTOOBJECT.fields_by_name['uv'].message_type = _PROTOVECTOR2
DESCRIPTOR.message_types_by_name['ProtoRobot'] = _PROTOROBOT
DESCRIPTOR.message_types_by_name['ProtoField'] = _PROTOFIELD
DESCRIPTOR.message_types_by_name['ProtoNode'] = _PROTONODE
DESCRIPTOR.message_types_by_name['ProtoObject'] = _PROTOOBJECT
DESCRIPTOR.message_types_by_name['ProtoVector3'] = _PROTOVECTOR3
DESCRIPTOR.message_types_by_name['ProtoVector2'] = _PROTOVECTOR2
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtoRobot = _reflection.GeneratedProtocolMessageType('ProtoRobot', (_message.Message,), {
  'DESCRIPTOR' : _PROTOROBOT,
  '__module__' : 'ProtoRobot_pb2'
  # @@protoc_insertion_point(class_scope:Synthesis.Simulator.ProtoRobot)
  })
_sym_db.RegisterMessage(ProtoRobot)

ProtoField = _reflection.GeneratedProtocolMessageType('ProtoField', (_message.Message,), {
  'DESCRIPTOR' : _PROTOFIELD,
  '__module__' : 'ProtoRobot_pb2'
  # @@protoc_insertion_point(class_scope:Synthesis.Simulator.ProtoField)
  })
_sym_db.RegisterMessage(ProtoField)

ProtoNode = _reflection.GeneratedProtocolMessageType('ProtoNode', (_message.Message,), {
  'DESCRIPTOR' : _PROTONODE,
  '__module__' : 'ProtoRobot_pb2'
  # @@protoc_insertion_point(class_scope:Synthesis.Simulator.ProtoNode)
  })
_sym_db.RegisterMessage(ProtoNode)

ProtoObject = _reflection.GeneratedProtocolMessageType('ProtoObject', (_message.Message,), {
  'DESCRIPTOR' : _PROTOOBJECT,
  '__module__' : 'ProtoRobot_pb2'
  # @@protoc_insertion_point(class_scope:Synthesis.Simulator.ProtoObject)
  })
_sym_db.RegisterMessage(ProtoObject)

ProtoVector3 = _reflection.GeneratedProtocolMessageType('ProtoVector3', (_message.Message,), {
  'DESCRIPTOR' : _PROTOVECTOR3,
  '__module__' : 'ProtoRobot_pb2'
  # @@protoc_insertion_point(class_scope:Synthesis.Simulator.ProtoVector3)
  })
_sym_db.RegisterMessage(ProtoVector3)

ProtoVector2 = _reflection.GeneratedProtocolMessageType('ProtoVector2', (_message.Message,), {
  'DESCRIPTOR' : _PROTOVECTOR2,
  '__module__' : 'ProtoRobot_pb2'
  # @@protoc_insertion_point(class_scope:Synthesis.Simulator.ProtoVector2)
  })
_sym_db.RegisterMessage(ProtoVector2)


# @@protoc_insertion_point(module_scope)
