// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: material.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mirabuf {

  /// <summary>Holder for reflection information generated from material.proto</summary>
  public static partial class MaterialReflection {

    #region Descriptor
    /// <summary>File descriptor for material.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MaterialReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5tYXRlcmlhbC5wcm90bxIHbWlyYWJ1ZhoLdHlwZXMucHJvdG8iowEKCU1h",
            "dGVyaWFscxIbCgRpbmZvGAEgASgLMg0ubWlyYWJ1Zi5JbmZvEjQKCW1hdGVy",
            "aWFscxgCIAMoCzIhLm1pcmFidWYuTWF0ZXJpYWxzLk1hdGVyaWFsc0VudHJ5",
            "GkMKDk1hdGVyaWFsc0VudHJ5EgsKA2tleRgBIAEoCRIgCgV2YWx1ZRgCIAEo",
            "CzIRLm1pcmFidWYuTWF0ZXJpYWw6AjgBIoUBCghNYXRlcmlhbBIbCgRpbmZv",
            "GAEgASgLMg0ubWlyYWJ1Zi5JbmZvEicKCmFwcGVhcmFuY2UYAiABKAsyEy5t",
            "aXJhYnVmLkFwcGVhcmFuY2USMwoQcGh5c2ljYWxNYXRlcmlhbBgDIAEoCzIZ",
            "Lm1pcmFidWYuUGh5c2ljYWxNYXRlcmlhbCJjCgpBcHBlYXJhbmNlEh4KBmFs",
            "YmVkbxgBIAEoCzIOLm1pcmFidWYuQ29sb3ISEQoJcm91Z2huZXNzGAIgASgC",
            "EhAKCG1ldGFsbGljGAMgASgCEhAKCHNwZWN1bGFyGAQgASgCIswFChBQaHlz",
            "aWNhbE1hdGVyaWFsEgwKBG5hbWUYASABKAkSEwoLZGVzY3JpcHRpb24YAiAB",
            "KAkSMgoHdGhlcm1hbBgDIAEoCzIhLm1pcmFidWYuUGh5c2ljYWxNYXRlcmlh",
            "bC5UaGVybWFsEjgKCm1lY2hhbmljYWwYBCABKAsyJC5taXJhYnVmLlBoeXNp",
            "Y2FsTWF0ZXJpYWwuTWVjaGFuaWNhbBI0CghzdHJlbmd0aBgFIAEoCzIiLm1p",
            "cmFidWYuUGh5c2ljYWxNYXRlcmlhbC5TdHJlbmd0aBIYChBkeW5hbWljX2Zy",
            "aWN0aW9uGAYgASgCEhcKD3N0YXRpY19mcmljdGlvbhgHIAEoAhITCgtyZXN0",
            "aXR1dGlvbhgIIAEoAhISCgpkZWZvcm1hYmxlGAkgASgIEjQKBHR5cGUYCiAB",
            "KA4yJi5taXJhYnVmLlBoeXNpY2FsTWF0ZXJpYWwuTWF0ZXJpYWxUeXBlGmUK",
            "B1RoZXJtYWwSHAoUdGhlcm1hbF9jb25kdWN0aXZpdHkYASABKAISFQoNc3Bl",
            "Y2lmaWNfaGVhdBgCIAEoAhIlCh10aGVybWFsX2V4cGFuc2lvbl9jb2VmZmlj",
            "aWVudBgDIAEoAhp3CgpNZWNoYW5pY2FsEhEKCXlvdW5nX21vZBgBIAEoAhIV",
            "Cg1wb2lzc29uX3JhdGlvGAIgASgCEhEKCXNoZWFyX21vZBgDIAEoAhIPCgdk",
            "ZW5zaXR5GAQgASgCEhsKE2RhbXBpbmdfY29lZmZpY2llbnQYBSABKAIaVwoI",
            "U3RyZW5ndGgSFgoOeWllbGRfc3RyZW5ndGgYASABKAISGAoQdGVuc2lsZV9z",
            "dHJlbmd0aBgCIAEoAhIZChF0aGVybWFsX3RyZWF0bWVudBgDIAEoCCImCgxN",
            "YXRlcmlhbFR5cGUSCQoFTUVUQUwQABILCgdQTEFTVElDEAFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Mirabuf.TypesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mirabuf.Materials), global::Mirabuf.Materials.Parser, new[]{ "Info", "Materials_" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mirabuf.Material), global::Mirabuf.Material.Parser, new[]{ "Info", "Appearance", "PhysicalMaterial" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mirabuf.Appearance), global::Mirabuf.Appearance.Parser, new[]{ "Albedo", "Roughness", "Metallic", "Specular" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mirabuf.PhysicalMaterial), global::Mirabuf.PhysicalMaterial.Parser, new[]{ "Name", "Description", "Thermal", "Mechanical", "Strength", "DynamicFriction", "StaticFriction", "Restitution", "Deformable", "Type" }, null, new[]{ typeof(global::Mirabuf.PhysicalMaterial.Types.MaterialType) }, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Mirabuf.PhysicalMaterial.Types.Thermal), global::Mirabuf.PhysicalMaterial.Types.Thermal.Parser, new[]{ "ThermalConductivity", "SpecificHeat", "ThermalExpansionCoefficient" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mirabuf.PhysicalMaterial.Types.Mechanical), global::Mirabuf.PhysicalMaterial.Types.Mechanical.Parser, new[]{ "YoungMod", "PoissonRatio", "ShearMod", "Density", "DampingCoefficient" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mirabuf.PhysicalMaterial.Types.Strength), global::Mirabuf.PhysicalMaterial.Types.Strength.Parser, new[]{ "YieldStrength", "TensileStrength", "ThermalTreatment" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  ///*
  /// Represents a File or Set of Materials with Appearances and Physical Data
  /// 
  /// Can be Stored in AssemblyData
  /// </summary>
  public sealed partial class Materials : pb::IMessage<Materials>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Materials> _parser = new pb::MessageParser<Materials>(() => new Materials());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Materials> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mirabuf.MaterialReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Materials() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Materials(Materials other) : this() {
      info_ = other.info_ != null ? other.info_.Clone() : null;
      materials_ = other.materials_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Materials Clone() {
      return new Materials(this);
    }

    /// <summary>Field number for the "info" field.</summary>
    public const int InfoFieldNumber = 1;
    private global::Mirabuf.Info info_;
    /// <summary>
    /// file info
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mirabuf.Info Info {
      get { return info_; }
      set {
        info_ = value;
      }
    }

    /// <summary>Field number for the "materials" field.</summary>
    public const int Materials_FieldNumber = 2;
    private static readonly pbc::MapField<string, global::Mirabuf.Material>.Codec _map_materials_codec
        = new pbc::MapField<string, global::Mirabuf.Material>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForMessage(18, global::Mirabuf.Material.Parser), 18);
    private readonly pbc::MapField<string, global::Mirabuf.Material> materials_ = new pbc::MapField<string, global::Mirabuf.Material>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, global::Mirabuf.Material> Materials_ {
      get { return materials_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Materials);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Materials other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Info, other.Info)) return false;
      if (!Materials_.Equals(other.Materials_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (info_ != null) hash ^= Info.GetHashCode();
      hash ^= Materials_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (info_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Info);
      }
      materials_.WriteTo(output, _map_materials_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (info_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Info);
      }
      materials_.WriteTo(ref output, _map_materials_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (info_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Info);
      }
      size += materials_.CalculateSize(_map_materials_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Materials other) {
      if (other == null) {
        return;
      }
      if (other.info_ != null) {
        if (info_ == null) {
          Info = new global::Mirabuf.Info();
        }
        Info.MergeFrom(other.Info);
      }
      materials_.Add(other.materials_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (info_ == null) {
              Info = new global::Mirabuf.Info();
            }
            input.ReadMessage(Info);
            break;
          }
          case 18: {
            materials_.AddEntriesFrom(input, _map_materials_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (info_ == null) {
              Info = new global::Mirabuf.Info();
            }
            input.ReadMessage(Info);
            break;
          }
          case 18: {
            materials_.AddEntriesFrom(ref input, _map_materials_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///*
  /// Contains the information regarding the appearance and physical properties
  /// </summary>
  public sealed partial class Material : pb::IMessage<Material>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Material> _parser = new pb::MessageParser<Material>(() => new Material());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Material> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mirabuf.MaterialReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Material() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Material(Material other) : this() {
      info_ = other.info_ != null ? other.info_.Clone() : null;
      appearance_ = other.appearance_ != null ? other.appearance_.Clone() : null;
      physicalMaterial_ = other.physicalMaterial_ != null ? other.physicalMaterial_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Material Clone() {
      return new Material(this);
    }

    /// <summary>Field number for the "info" field.</summary>
    public const int InfoFieldNumber = 1;
    private global::Mirabuf.Info info_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mirabuf.Info Info {
      get { return info_; }
      set {
        info_ = value;
      }
    }

    /// <summary>Field number for the "appearance" field.</summary>
    public const int AppearanceFieldNumber = 2;
    private global::Mirabuf.Appearance appearance_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mirabuf.Appearance Appearance {
      get { return appearance_; }
      set {
        appearance_ = value;
      }
    }

    /// <summary>Field number for the "physicalMaterial" field.</summary>
    public const int PhysicalMaterialFieldNumber = 3;
    private global::Mirabuf.PhysicalMaterial physicalMaterial_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mirabuf.PhysicalMaterial PhysicalMaterial {
      get { return physicalMaterial_; }
      set {
        physicalMaterial_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Material);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Material other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Info, other.Info)) return false;
      if (!object.Equals(Appearance, other.Appearance)) return false;
      if (!object.Equals(PhysicalMaterial, other.PhysicalMaterial)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (info_ != null) hash ^= Info.GetHashCode();
      if (appearance_ != null) hash ^= Appearance.GetHashCode();
      if (physicalMaterial_ != null) hash ^= PhysicalMaterial.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (info_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Info);
      }
      if (appearance_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Appearance);
      }
      if (physicalMaterial_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(PhysicalMaterial);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (info_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Info);
      }
      if (appearance_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Appearance);
      }
      if (physicalMaterial_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(PhysicalMaterial);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (info_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Info);
      }
      if (appearance_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Appearance);
      }
      if (physicalMaterial_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PhysicalMaterial);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Material other) {
      if (other == null) {
        return;
      }
      if (other.info_ != null) {
        if (info_ == null) {
          Info = new global::Mirabuf.Info();
        }
        Info.MergeFrom(other.Info);
      }
      if (other.appearance_ != null) {
        if (appearance_ == null) {
          Appearance = new global::Mirabuf.Appearance();
        }
        Appearance.MergeFrom(other.Appearance);
      }
      if (other.physicalMaterial_ != null) {
        if (physicalMaterial_ == null) {
          PhysicalMaterial = new global::Mirabuf.PhysicalMaterial();
        }
        PhysicalMaterial.MergeFrom(other.PhysicalMaterial);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (info_ == null) {
              Info = new global::Mirabuf.Info();
            }
            input.ReadMessage(Info);
            break;
          }
          case 18: {
            if (appearance_ == null) {
              Appearance = new global::Mirabuf.Appearance();
            }
            input.ReadMessage(Appearance);
            break;
          }
          case 26: {
            if (physicalMaterial_ == null) {
              PhysicalMaterial = new global::Mirabuf.PhysicalMaterial();
            }
            input.ReadMessage(PhysicalMaterial);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (info_ == null) {
              Info = new global::Mirabuf.Info();
            }
            input.ReadMessage(Info);
            break;
          }
          case 18: {
            if (appearance_ == null) {
              Appearance = new global::Mirabuf.Appearance();
            }
            input.ReadMessage(Appearance);
            break;
          }
          case 26: {
            if (physicalMaterial_ == null) {
              PhysicalMaterial = new global::Mirabuf.PhysicalMaterial();
            }
            input.ReadMessage(PhysicalMaterial);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///*
  /// Contains information on how a object looks
  /// Limited to just color for now
  /// </summary>
  public sealed partial class Appearance : pb::IMessage<Appearance>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Appearance> _parser = new pb::MessageParser<Appearance>(() => new Appearance());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Appearance> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mirabuf.MaterialReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Appearance() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Appearance(Appearance other) : this() {
      albedo_ = other.albedo_ != null ? other.albedo_.Clone() : null;
      roughness_ = other.roughness_;
      metallic_ = other.metallic_;
      specular_ = other.specular_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Appearance Clone() {
      return new Appearance(this);
    }

    /// <summary>Field number for the "albedo" field.</summary>
    public const int AlbedoFieldNumber = 1;
    private global::Mirabuf.Color albedo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mirabuf.Color Albedo {
      get { return albedo_; }
      set {
        albedo_ = value;
      }
    }

    /// <summary>Field number for the "roughness" field.</summary>
    public const int RoughnessFieldNumber = 2;
    private float roughness_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Roughness {
      get { return roughness_; }
      set {
        roughness_ = value;
      }
    }

    /// <summary>Field number for the "metallic" field.</summary>
    public const int MetallicFieldNumber = 3;
    private float metallic_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Metallic {
      get { return metallic_; }
      set {
        metallic_ = value;
      }
    }

    /// <summary>Field number for the "specular" field.</summary>
    public const int SpecularFieldNumber = 4;
    private float specular_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Specular {
      get { return specular_; }
      set {
        specular_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Appearance);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Appearance other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Albedo, other.Albedo)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Roughness, other.Roughness)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Metallic, other.Metallic)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Specular, other.Specular)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (albedo_ != null) hash ^= Albedo.GetHashCode();
      if (Roughness != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Roughness);
      if (Metallic != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Metallic);
      if (Specular != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Specular);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (albedo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Albedo);
      }
      if (Roughness != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Roughness);
      }
      if (Metallic != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Metallic);
      }
      if (Specular != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(Specular);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (albedo_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Albedo);
      }
      if (Roughness != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Roughness);
      }
      if (Metallic != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Metallic);
      }
      if (Specular != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(Specular);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (albedo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Albedo);
      }
      if (Roughness != 0F) {
        size += 1 + 4;
      }
      if (Metallic != 0F) {
        size += 1 + 4;
      }
      if (Specular != 0F) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Appearance other) {
      if (other == null) {
        return;
      }
      if (other.albedo_ != null) {
        if (albedo_ == null) {
          Albedo = new global::Mirabuf.Color();
        }
        Albedo.MergeFrom(other.Albedo);
      }
      if (other.Roughness != 0F) {
        Roughness = other.Roughness;
      }
      if (other.Metallic != 0F) {
        Metallic = other.Metallic;
      }
      if (other.Specular != 0F) {
        Specular = other.Specular;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (albedo_ == null) {
              Albedo = new global::Mirabuf.Color();
            }
            input.ReadMessage(Albedo);
            break;
          }
          case 21: {
            Roughness = input.ReadFloat();
            break;
          }
          case 29: {
            Metallic = input.ReadFloat();
            break;
          }
          case 37: {
            Specular = input.ReadFloat();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (albedo_ == null) {
              Albedo = new global::Mirabuf.Color();
            }
            input.ReadMessage(Albedo);
            break;
          }
          case 21: {
            Roughness = input.ReadFloat();
            break;
          }
          case 29: {
            Metallic = input.ReadFloat();
            break;
          }
          case 37: {
            Specular = input.ReadFloat();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///*
  /// Data to represent any given Physical Material
  /// </summary>
  public sealed partial class PhysicalMaterial : pb::IMessage<PhysicalMaterial>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PhysicalMaterial> _parser = new pb::MessageParser<PhysicalMaterial>(() => new PhysicalMaterial());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PhysicalMaterial> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mirabuf.MaterialReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PhysicalMaterial() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PhysicalMaterial(PhysicalMaterial other) : this() {
      name_ = other.name_;
      description_ = other.description_;
      thermal_ = other.thermal_ != null ? other.thermal_.Clone() : null;
      mechanical_ = other.mechanical_ != null ? other.mechanical_.Clone() : null;
      strength_ = other.strength_ != null ? other.strength_.Clone() : null;
      dynamicFriction_ = other.dynamicFriction_;
      staticFriction_ = other.staticFriction_;
      restitution_ = other.restitution_;
      deformable_ = other.deformable_;
      type_ = other.type_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PhysicalMaterial Clone() {
      return new PhysicalMaterial(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 2;
    private string description_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "thermal" field.</summary>
    public const int ThermalFieldNumber = 3;
    private global::Mirabuf.PhysicalMaterial.Types.Thermal thermal_;
    /// <summary>
    //// Thermal Physical properties of the model
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mirabuf.PhysicalMaterial.Types.Thermal Thermal {
      get { return thermal_; }
      set {
        thermal_ = value;
      }
    }

    /// <summary>Field number for the "mechanical" field.</summary>
    public const int MechanicalFieldNumber = 4;
    private global::Mirabuf.PhysicalMaterial.Types.Mechanical mechanical_;
    /// <summary>
    //// Mechanical properties of the model
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mirabuf.PhysicalMaterial.Types.Mechanical Mechanical {
      get { return mechanical_; }
      set {
        mechanical_ = value;
      }
    }

    /// <summary>Field number for the "strength" field.</summary>
    public const int StrengthFieldNumber = 5;
    private global::Mirabuf.PhysicalMaterial.Types.Strength strength_;
    /// <summary>
    //// Physical Strength properties of the model=
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mirabuf.PhysicalMaterial.Types.Strength Strength {
      get { return strength_; }
      set {
        strength_ = value;
      }
    }

    /// <summary>Field number for the "dynamic_friction" field.</summary>
    public const int DynamicFrictionFieldNumber = 6;
    private float dynamicFriction_;
    /// <summary>
    //// Frictional force for dampening - Interpolate (0-1)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float DynamicFriction {
      get { return dynamicFriction_; }
      set {
        dynamicFriction_ = value;
      }
    }

    /// <summary>Field number for the "static_friction" field.</summary>
    public const int StaticFrictionFieldNumber = 7;
    private float staticFriction_;
    /// <summary>
    //// Frictional force override at stop - Interpolate (0-1)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float StaticFriction {
      get { return staticFriction_; }
      set {
        staticFriction_ = value;
      }
    }

    /// <summary>Field number for the "restitution" field.</summary>
    public const int RestitutionFieldNumber = 8;
    private float restitution_;
    /// <summary>
    //// Restitution of the object - Interpolate (0-1)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Restitution {
      get { return restitution_; }
      set {
        restitution_ = value;
      }
    }

    /// <summary>Field number for the "deformable" field.</summary>
    public const int DeformableFieldNumber = 9;
    private bool deformable_;
    /// <summary>
    //// should this object deform when encountering large forces - TODO: This needs a proper message and equation field
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Deformable {
      get { return deformable_; }
      set {
        deformable_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 10;
    private global::Mirabuf.PhysicalMaterial.Types.MaterialType type_ = global::Mirabuf.PhysicalMaterial.Types.MaterialType.Metal;
    /// <summary>
    //// generic type to assign some default params
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mirabuf.PhysicalMaterial.Types.MaterialType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PhysicalMaterial);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PhysicalMaterial other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Description != other.Description) return false;
      if (!object.Equals(Thermal, other.Thermal)) return false;
      if (!object.Equals(Mechanical, other.Mechanical)) return false;
      if (!object.Equals(Strength, other.Strength)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(DynamicFriction, other.DynamicFriction)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(StaticFriction, other.StaticFriction)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Restitution, other.Restitution)) return false;
      if (Deformable != other.Deformable) return false;
      if (Type != other.Type) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      if (thermal_ != null) hash ^= Thermal.GetHashCode();
      if (mechanical_ != null) hash ^= Mechanical.GetHashCode();
      if (strength_ != null) hash ^= Strength.GetHashCode();
      if (DynamicFriction != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(DynamicFriction);
      if (StaticFriction != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(StaticFriction);
      if (Restitution != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Restitution);
      if (Deformable != false) hash ^= Deformable.GetHashCode();
      if (Type != global::Mirabuf.PhysicalMaterial.Types.MaterialType.Metal) hash ^= Type.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Description);
      }
      if (thermal_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Thermal);
      }
      if (mechanical_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Mechanical);
      }
      if (strength_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Strength);
      }
      if (DynamicFriction != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(DynamicFriction);
      }
      if (StaticFriction != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(StaticFriction);
      }
      if (Restitution != 0F) {
        output.WriteRawTag(69);
        output.WriteFloat(Restitution);
      }
      if (Deformable != false) {
        output.WriteRawTag(72);
        output.WriteBool(Deformable);
      }
      if (Type != global::Mirabuf.PhysicalMaterial.Types.MaterialType.Metal) {
        output.WriteRawTag(80);
        output.WriteEnum((int) Type);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Description);
      }
      if (thermal_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Thermal);
      }
      if (mechanical_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Mechanical);
      }
      if (strength_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Strength);
      }
      if (DynamicFriction != 0F) {
        output.WriteRawTag(53);
        output.WriteFloat(DynamicFriction);
      }
      if (StaticFriction != 0F) {
        output.WriteRawTag(61);
        output.WriteFloat(StaticFriction);
      }
      if (Restitution != 0F) {
        output.WriteRawTag(69);
        output.WriteFloat(Restitution);
      }
      if (Deformable != false) {
        output.WriteRawTag(72);
        output.WriteBool(Deformable);
      }
      if (Type != global::Mirabuf.PhysicalMaterial.Types.MaterialType.Metal) {
        output.WriteRawTag(80);
        output.WriteEnum((int) Type);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (thermal_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Thermal);
      }
      if (mechanical_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Mechanical);
      }
      if (strength_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Strength);
      }
      if (DynamicFriction != 0F) {
        size += 1 + 4;
      }
      if (StaticFriction != 0F) {
        size += 1 + 4;
      }
      if (Restitution != 0F) {
        size += 1 + 4;
      }
      if (Deformable != false) {
        size += 1 + 1;
      }
      if (Type != global::Mirabuf.PhysicalMaterial.Types.MaterialType.Metal) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PhysicalMaterial other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      if (other.thermal_ != null) {
        if (thermal_ == null) {
          Thermal = new global::Mirabuf.PhysicalMaterial.Types.Thermal();
        }
        Thermal.MergeFrom(other.Thermal);
      }
      if (other.mechanical_ != null) {
        if (mechanical_ == null) {
          Mechanical = new global::Mirabuf.PhysicalMaterial.Types.Mechanical();
        }
        Mechanical.MergeFrom(other.Mechanical);
      }
      if (other.strength_ != null) {
        if (strength_ == null) {
          Strength = new global::Mirabuf.PhysicalMaterial.Types.Strength();
        }
        Strength.MergeFrom(other.Strength);
      }
      if (other.DynamicFriction != 0F) {
        DynamicFriction = other.DynamicFriction;
      }
      if (other.StaticFriction != 0F) {
        StaticFriction = other.StaticFriction;
      }
      if (other.Restitution != 0F) {
        Restitution = other.Restitution;
      }
      if (other.Deformable != false) {
        Deformable = other.Deformable;
      }
      if (other.Type != global::Mirabuf.PhysicalMaterial.Types.MaterialType.Metal) {
        Type = other.Type;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Description = input.ReadString();
            break;
          }
          case 26: {
            if (thermal_ == null) {
              Thermal = new global::Mirabuf.PhysicalMaterial.Types.Thermal();
            }
            input.ReadMessage(Thermal);
            break;
          }
          case 34: {
            if (mechanical_ == null) {
              Mechanical = new global::Mirabuf.PhysicalMaterial.Types.Mechanical();
            }
            input.ReadMessage(Mechanical);
            break;
          }
          case 42: {
            if (strength_ == null) {
              Strength = new global::Mirabuf.PhysicalMaterial.Types.Strength();
            }
            input.ReadMessage(Strength);
            break;
          }
          case 53: {
            DynamicFriction = input.ReadFloat();
            break;
          }
          case 61: {
            StaticFriction = input.ReadFloat();
            break;
          }
          case 69: {
            Restitution = input.ReadFloat();
            break;
          }
          case 72: {
            Deformable = input.ReadBool();
            break;
          }
          case 80: {
            Type = (global::Mirabuf.PhysicalMaterial.Types.MaterialType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Description = input.ReadString();
            break;
          }
          case 26: {
            if (thermal_ == null) {
              Thermal = new global::Mirabuf.PhysicalMaterial.Types.Thermal();
            }
            input.ReadMessage(Thermal);
            break;
          }
          case 34: {
            if (mechanical_ == null) {
              Mechanical = new global::Mirabuf.PhysicalMaterial.Types.Mechanical();
            }
            input.ReadMessage(Mechanical);
            break;
          }
          case 42: {
            if (strength_ == null) {
              Strength = new global::Mirabuf.PhysicalMaterial.Types.Strength();
            }
            input.ReadMessage(Strength);
            break;
          }
          case 53: {
            DynamicFriction = input.ReadFloat();
            break;
          }
          case 61: {
            StaticFriction = input.ReadFloat();
            break;
          }
          case 69: {
            Restitution = input.ReadFloat();
            break;
          }
          case 72: {
            Deformable = input.ReadBool();
            break;
          }
          case 80: {
            Type = (global::Mirabuf.PhysicalMaterial.Types.MaterialType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the PhysicalMaterial message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum MaterialType {
        [pbr::OriginalName("METAL")] Metal = 0,
        [pbr::OriginalName("PLASTIC")] Plastic = 1,
      }

      public sealed partial class Thermal : pb::IMessage<Thermal>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Thermal> _parser = new pb::MessageParser<Thermal>(() => new Thermal());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Thermal> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Mirabuf.PhysicalMaterial.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Thermal() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Thermal(Thermal other) : this() {
          thermalConductivity_ = other.thermalConductivity_;
          specificHeat_ = other.specificHeat_;
          thermalExpansionCoefficient_ = other.thermalExpansionCoefficient_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Thermal Clone() {
          return new Thermal(this);
        }

        /// <summary>Field number for the "thermal_conductivity" field.</summary>
        public const int ThermalConductivityFieldNumber = 1;
        private float thermalConductivity_;
        /// <summary>
        //// W/(m*K)
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float ThermalConductivity {
          get { return thermalConductivity_; }
          set {
            thermalConductivity_ = value;
          }
        }

        /// <summary>Field number for the "specific_heat" field.</summary>
        public const int SpecificHeatFieldNumber = 2;
        private float specificHeat_;
        /// <summary>
        //// J/(g*C)
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float SpecificHeat {
          get { return specificHeat_; }
          set {
            specificHeat_ = value;
          }
        }

        /// <summary>Field number for the "thermal_expansion_coefficient" field.</summary>
        public const int ThermalExpansionCoefficientFieldNumber = 3;
        private float thermalExpansionCoefficient_;
        /// <summary>
        //// um/(m*C)
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float ThermalExpansionCoefficient {
          get { return thermalExpansionCoefficient_; }
          set {
            thermalExpansionCoefficient_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Thermal);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Thermal other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(ThermalConductivity, other.ThermalConductivity)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(SpecificHeat, other.SpecificHeat)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(ThermalExpansionCoefficient, other.ThermalExpansionCoefficient)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (ThermalConductivity != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(ThermalConductivity);
          if (SpecificHeat != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(SpecificHeat);
          if (ThermalExpansionCoefficient != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(ThermalExpansionCoefficient);
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (ThermalConductivity != 0F) {
            output.WriteRawTag(13);
            output.WriteFloat(ThermalConductivity);
          }
          if (SpecificHeat != 0F) {
            output.WriteRawTag(21);
            output.WriteFloat(SpecificHeat);
          }
          if (ThermalExpansionCoefficient != 0F) {
            output.WriteRawTag(29);
            output.WriteFloat(ThermalExpansionCoefficient);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (ThermalConductivity != 0F) {
            output.WriteRawTag(13);
            output.WriteFloat(ThermalConductivity);
          }
          if (SpecificHeat != 0F) {
            output.WriteRawTag(21);
            output.WriteFloat(SpecificHeat);
          }
          if (ThermalExpansionCoefficient != 0F) {
            output.WriteRawTag(29);
            output.WriteFloat(ThermalExpansionCoefficient);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (ThermalConductivity != 0F) {
            size += 1 + 4;
          }
          if (SpecificHeat != 0F) {
            size += 1 + 4;
          }
          if (ThermalExpansionCoefficient != 0F) {
            size += 1 + 4;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Thermal other) {
          if (other == null) {
            return;
          }
          if (other.ThermalConductivity != 0F) {
            ThermalConductivity = other.ThermalConductivity;
          }
          if (other.SpecificHeat != 0F) {
            SpecificHeat = other.SpecificHeat;
          }
          if (other.ThermalExpansionCoefficient != 0F) {
            ThermalExpansionCoefficient = other.ThermalExpansionCoefficient;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 13: {
                ThermalConductivity = input.ReadFloat();
                break;
              }
              case 21: {
                SpecificHeat = input.ReadFloat();
                break;
              }
              case 29: {
                ThermalExpansionCoefficient = input.ReadFloat();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 13: {
                ThermalConductivity = input.ReadFloat();
                break;
              }
              case 21: {
                SpecificHeat = input.ReadFloat();
                break;
              }
              case 29: {
                ThermalExpansionCoefficient = input.ReadFloat();
                break;
              }
            }
          }
        }
        #endif

      }

      public sealed partial class Mechanical : pb::IMessage<Mechanical>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Mechanical> _parser = new pb::MessageParser<Mechanical>(() => new Mechanical());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Mechanical> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Mirabuf.PhysicalMaterial.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Mechanical() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Mechanical(Mechanical other) : this() {
          youngMod_ = other.youngMod_;
          poissonRatio_ = other.poissonRatio_;
          shearMod_ = other.shearMod_;
          density_ = other.density_;
          dampingCoefficient_ = other.dampingCoefficient_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Mechanical Clone() {
          return new Mechanical(this);
        }

        /// <summary>Field number for the "young_mod" field.</summary>
        public const int YoungModFieldNumber = 1;
        private float youngMod_;
        /// <summary>
        /// naming scheme changes here
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float YoungMod {
          get { return youngMod_; }
          set {
            youngMod_ = value;
          }
        }

        /// <summary>Field number for the "poisson_ratio" field.</summary>
        public const int PoissonRatioFieldNumber = 2;
        private float poissonRatio_;
        /// <summary>
        //// ?
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float PoissonRatio {
          get { return poissonRatio_; }
          set {
            poissonRatio_ = value;
          }
        }

        /// <summary>Field number for the "shear_mod" field.</summary>
        public const int ShearModFieldNumber = 3;
        private float shearMod_;
        /// <summary>
        //// MPa
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float ShearMod {
          get { return shearMod_; }
          set {
            shearMod_ = value;
          }
        }

        /// <summary>Field number for the "density" field.</summary>
        public const int DensityFieldNumber = 4;
        private float density_;
        /// <summary>
        //// g/cm^3
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float Density {
          get { return density_; }
          set {
            density_ = value;
          }
        }

        /// <summary>Field number for the "damping_coefficient" field.</summary>
        public const int DampingCoefficientFieldNumber = 5;
        private float dampingCoefficient_;
        /// <summary>
        /// ?
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float DampingCoefficient {
          get { return dampingCoefficient_; }
          set {
            dampingCoefficient_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Mechanical);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Mechanical other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(YoungMod, other.YoungMod)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(PoissonRatio, other.PoissonRatio)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(ShearMod, other.ShearMod)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Density, other.Density)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(DampingCoefficient, other.DampingCoefficient)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (YoungMod != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(YoungMod);
          if (PoissonRatio != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(PoissonRatio);
          if (ShearMod != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(ShearMod);
          if (Density != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Density);
          if (DampingCoefficient != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(DampingCoefficient);
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (YoungMod != 0F) {
            output.WriteRawTag(13);
            output.WriteFloat(YoungMod);
          }
          if (PoissonRatio != 0F) {
            output.WriteRawTag(21);
            output.WriteFloat(PoissonRatio);
          }
          if (ShearMod != 0F) {
            output.WriteRawTag(29);
            output.WriteFloat(ShearMod);
          }
          if (Density != 0F) {
            output.WriteRawTag(37);
            output.WriteFloat(Density);
          }
          if (DampingCoefficient != 0F) {
            output.WriteRawTag(45);
            output.WriteFloat(DampingCoefficient);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (YoungMod != 0F) {
            output.WriteRawTag(13);
            output.WriteFloat(YoungMod);
          }
          if (PoissonRatio != 0F) {
            output.WriteRawTag(21);
            output.WriteFloat(PoissonRatio);
          }
          if (ShearMod != 0F) {
            output.WriteRawTag(29);
            output.WriteFloat(ShearMod);
          }
          if (Density != 0F) {
            output.WriteRawTag(37);
            output.WriteFloat(Density);
          }
          if (DampingCoefficient != 0F) {
            output.WriteRawTag(45);
            output.WriteFloat(DampingCoefficient);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (YoungMod != 0F) {
            size += 1 + 4;
          }
          if (PoissonRatio != 0F) {
            size += 1 + 4;
          }
          if (ShearMod != 0F) {
            size += 1 + 4;
          }
          if (Density != 0F) {
            size += 1 + 4;
          }
          if (DampingCoefficient != 0F) {
            size += 1 + 4;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Mechanical other) {
          if (other == null) {
            return;
          }
          if (other.YoungMod != 0F) {
            YoungMod = other.YoungMod;
          }
          if (other.PoissonRatio != 0F) {
            PoissonRatio = other.PoissonRatio;
          }
          if (other.ShearMod != 0F) {
            ShearMod = other.ShearMod;
          }
          if (other.Density != 0F) {
            Density = other.Density;
          }
          if (other.DampingCoefficient != 0F) {
            DampingCoefficient = other.DampingCoefficient;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 13: {
                YoungMod = input.ReadFloat();
                break;
              }
              case 21: {
                PoissonRatio = input.ReadFloat();
                break;
              }
              case 29: {
                ShearMod = input.ReadFloat();
                break;
              }
              case 37: {
                Density = input.ReadFloat();
                break;
              }
              case 45: {
                DampingCoefficient = input.ReadFloat();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 13: {
                YoungMod = input.ReadFloat();
                break;
              }
              case 21: {
                PoissonRatio = input.ReadFloat();
                break;
              }
              case 29: {
                ShearMod = input.ReadFloat();
                break;
              }
              case 37: {
                Density = input.ReadFloat();
                break;
              }
              case 45: {
                DampingCoefficient = input.ReadFloat();
                break;
              }
            }
          }
        }
        #endif

      }

      public sealed partial class Strength : pb::IMessage<Strength>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<Strength> _parser = new pb::MessageParser<Strength>(() => new Strength());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<Strength> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Mirabuf.PhysicalMaterial.Descriptor.NestedTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Strength() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Strength(Strength other) : this() {
          yieldStrength_ = other.yieldStrength_;
          tensileStrength_ = other.tensileStrength_;
          thermalTreatment_ = other.thermalTreatment_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public Strength Clone() {
          return new Strength(this);
        }

        /// <summary>Field number for the "yield_strength" field.</summary>
        public const int YieldStrengthFieldNumber = 1;
        private float yieldStrength_;
        /// <summary>
        //// MPa
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float YieldStrength {
          get { return yieldStrength_; }
          set {
            yieldStrength_ = value;
          }
        }

        /// <summary>Field number for the "tensile_strength" field.</summary>
        public const int TensileStrengthFieldNumber = 2;
        private float tensileStrength_;
        /// <summary>
        //// MPa
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public float TensileStrength {
          get { return tensileStrength_; }
          set {
            tensileStrength_ = value;
          }
        }

        /// <summary>Field number for the "thermal_treatment" field.</summary>
        public const int ThermalTreatmentFieldNumber = 3;
        private bool thermalTreatment_;
        /// <summary>
        //// yes / no
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool ThermalTreatment {
          get { return thermalTreatment_; }
          set {
            thermalTreatment_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as Strength);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(Strength other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(YieldStrength, other.YieldStrength)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(TensileStrength, other.TensileStrength)) return false;
          if (ThermalTreatment != other.ThermalTreatment) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          if (YieldStrength != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(YieldStrength);
          if (TensileStrength != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(TensileStrength);
          if (ThermalTreatment != false) hash ^= ThermalTreatment.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          if (YieldStrength != 0F) {
            output.WriteRawTag(13);
            output.WriteFloat(YieldStrength);
          }
          if (TensileStrength != 0F) {
            output.WriteRawTag(21);
            output.WriteFloat(TensileStrength);
          }
          if (ThermalTreatment != false) {
            output.WriteRawTag(24);
            output.WriteBool(ThermalTreatment);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          if (YieldStrength != 0F) {
            output.WriteRawTag(13);
            output.WriteFloat(YieldStrength);
          }
          if (TensileStrength != 0F) {
            output.WriteRawTag(21);
            output.WriteFloat(TensileStrength);
          }
          if (ThermalTreatment != false) {
            output.WriteRawTag(24);
            output.WriteBool(ThermalTreatment);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          if (YieldStrength != 0F) {
            size += 1 + 4;
          }
          if (TensileStrength != 0F) {
            size += 1 + 4;
          }
          if (ThermalTreatment != false) {
            size += 1 + 1;
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(Strength other) {
          if (other == null) {
            return;
          }
          if (other.YieldStrength != 0F) {
            YieldStrength = other.YieldStrength;
          }
          if (other.TensileStrength != 0F) {
            TensileStrength = other.TensileStrength;
          }
          if (other.ThermalTreatment != false) {
            ThermalTreatment = other.ThermalTreatment;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 13: {
                YieldStrength = input.ReadFloat();
                break;
              }
              case 21: {
                TensileStrength = input.ReadFloat();
                break;
              }
              case 24: {
                ThermalTreatment = input.ReadBool();
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 13: {
                YieldStrength = input.ReadFloat();
                break;
              }
              case 21: {
                TensileStrength = input.ReadFloat();
                break;
              }
              case 24: {
                ThermalTreatment = input.ReadBool();
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
