#!/bin/sh

HERE="$(dirname "$(readlink -f "${0}")")"

mkdir ~/.config/Autodesk/Synthesis/Mira/Fields
cp $(HERE)/fields/* ~/.config/Autodesk/Synthesis/Mira/Fields
cp $(HERE)/robots/* ~/.config/Autodesk/Synthesis/Mira/
