#!/bin/sh

HERE="$(dirname "$(readlink -f "${0}")")"
EXEC="$HERE/usr/bin/Synthesis.x86_64"

mkdir -p ~/.config/Autodesk/Synthesis/Mira/Fields
cp "$HERE/fields/"*.mira ~/.config/Autodesk/Synthesis/Mira/Fields
cp "$HERE/robots/"*.mira ~/.config/Autodesk/Synthesis/Mira/

exec "$EXEC"
