.TH "BXDBox" 3 "Wed Jul 19 2017" "SimulatorAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BXDBox
.SH SYNOPSIS
.br
.PP
.PP
Inherits IComparable< BXDBox >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBXDBox\fP (double passMinX, double passMinY, double passMinZ, double passMaxX, double passMaxY, double passMaxZ)"
.br
.ti -1c
.RI "\fBBXDBox\fP (\fBBXDVector3\fP passMinPoint, \fBBXDVector3\fP passMaxPoint)"
.br
.ti -1c
.RI "float \fBGetPossibleRadius\fP ()"
.br
.ti -1c
.RI "int \fBCompareTo\fP (\fBBXDBox\fP other)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for SimulatorAPI from the source code\&.
