.TH "BXDQuaternion" 3 "Wed Jul 19 2017" "SimulatorAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BXDQuaternion
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBXDQuaternion\fP ()"
.br
.RI "Initializes a new instance of the \fBBXDQuaternion\fP class with an identity value\&. "
.ti -1c
.RI "\fBBXDQuaternion\fP (float x, float y, float z, float w)"
.br
.RI "Initializes a new instance of the \fBBXDQuaternion\fP class with the values given\&. "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "Returns a string containing labeled x, y, z, and w values\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBX\fP"
.br
.RI "The X value of the \fBBXDQuaternion\fP\&. "
.ti -1c
.RI "float \fBY\fP"
.br
.RI "The Y value of the \fBBXDQuaternion\fP\&. "
.ti -1c
.RI "float \fBZ\fP"
.br
.RI "The Z value of the \fBBXDQuaternion\fP\&. "
.ti -1c
.RI "float \fBW\fP"
.br
.RI "The W value of the \fBBXDQuaternion\fP\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BXDQuaternion\&.BXDQuaternion ()"

.PP
Initializes a new instance of the \fBBXDQuaternion\fP class with an identity value\&. 
.SS "BXDQuaternion\&.BXDQuaternion (float x, float y, float z, float w)"

.PP
Initializes a new instance of the \fBBXDQuaternion\fP class with the values given\&. 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP 
.br
\fIy\fP 
.br
\fIz\fP 
.br
\fIw\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "override string BXDQuaternion\&.ToString ()"

.PP
Returns a string containing labeled x, y, z, and w values\&. 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "float BXDQuaternion\&.W"

.PP
The W value of the \fBBXDQuaternion\fP\&. 
.SS "float BXDQuaternion\&.X"

.PP
The X value of the \fBBXDQuaternion\fP\&. 
.SS "float BXDQuaternion\&.Y"

.PP
The Y value of the \fBBXDQuaternion\fP\&. 
.SS "float BXDQuaternion\&.Z"

.PP
The Z value of the \fBBXDQuaternion\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SimulatorAPI from the source code\&.
