.TH "ElevatorDriverMeta" 3 "Wed Jul 19 2017" "SimulatorAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ElevatorDriverMeta
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBJointDriverMeta\fP\&.
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "ElevatorType \fBtype\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBWriteDataInternal\fP (System\&.IO\&.BinaryWriter writer)"
.br
.ti -1c
.RI "override void \fBReadDataInternal\fP (System\&.IO\&.BinaryReader reader)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SimulatorAPI from the source code\&.
