.TH "FieldNode" 3 "Wed Jul 19 2017" "SimulatorAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FieldNode
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFieldNode\fP (string nodeID, string physicsGroupID=\fBBXDFProperties\&.BXDF_DEFAULT_NAME\fP)"
.br
.RI "Constructs a new instance of the \fBFieldNode\fP class\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBNodeID\fP"
.br
.RI "The string ID for the node\&. "
.ti -1c
.RI "\fBBXDVector3\fP \fBPosition\fP"
.br
.RI "The initial position for the \fBFieldNode\fP\&. "
.ti -1c
.RI "\fBBXDQuaternion\fP \fBRotation\fP"
.br
.RI "The initial rotation for the \fBFieldNode\fP\&. "
.ti -1c
.RI "int \fBSubMeshID\fP"
.br
.RI "The sub mesh ID for the \fBFieldNode\fP\&. "
.ti -1c
.RI "int \fBCollisionMeshID\fP"
.br
.RI "The collision mesh ID for the \fBFieldNode\fP\&. "
.ti -1c
.RI "string \fBPropertySetID\fP"
.br
.RI "The string ID for the parent \fBPropertySet\fP\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FieldNode\&.FieldNode (string nodeID, string physicsGroupID = \fC\fBBXDFProperties\&.BXDF_DEFAULT_NAME\fP\fP)"

.PP
Constructs a new instance of the \fBFieldNode\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fInodeID\fP 
.br
\fIphysicsGroupID\fP 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "int FieldNode\&.CollisionMeshID"

.PP
The collision mesh ID for the \fBFieldNode\fP\&. 
.SS "string FieldNode\&.NodeID"

.PP
The string ID for the node\&. 
.SS "\fBBXDVector3\fP FieldNode\&.Position"

.PP
The initial position for the \fBFieldNode\fP\&. 
.SS "string FieldNode\&.PropertySetID"

.PP
The string ID for the parent \fBPropertySet\fP\&. 
.SS "\fBBXDQuaternion\fP FieldNode\&.Rotation"

.PP
The initial rotation for the \fBFieldNode\fP\&. 
.SS "int FieldNode\&.SubMeshID"

.PP
The sub mesh ID for the \fBFieldNode\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SimulatorAPI from the source code\&.
