.TH "FileUtilities" 3 "Wed Jul 19 2017" "SimulatorAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileUtilities
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBSanatizeFileName\fP (string fileName, char sanity='_')"
.br
.RI "Removes unsanitary characters from a file name and replaces them with sane ones\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static string FileUtilities\&.SanatizeFileName (string fileName, char sanity = \fC'_'\fP)\fC [static]\fP"

.PP
Removes unsanitary characters from a file name and replaces them with sane ones\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfileName\fP The filename
.br
\fIsanity\fP The optional character to replace with
.RE
.PP
\fBReturns:\fP
.RS 4
The sane filename
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for SimulatorAPI from the source code\&.
