.TH "LinearDOF" 3 "Wed Jul 19 2017" "SimulatorAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LinearDOF \- Contains information about a linear degree of freedom\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "float \fBcurrentPosition\fP\fC [get]\fP"
.br
.ti -1c
.RI "float \fBupperLimit\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "float \fBlowerLimit\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBBXDVector3\fP \fBtranslationalAxis\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "\fBBXDVector3\fP \fBbasePoint\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains information about a linear degree of freedom\&. 



.SH "Author"
.PP 
Generated automatically by Doxygen for SimulatorAPI from the source code\&.
