.TH "PropertySet.SphereCollider" 3 "Wed Jul 19 2017" "SimulatorAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PropertySet.SphereCollider
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPropertySet\&.PropertySetCollider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSphereCollider\fP (float scale)"
.br
.RI "Initializes a new instance of the \fBSphereCollider\fP class\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "float \fBScale\fP\fC [get]\fP"
.br
.RI "The scale of the \fBSphereCollider\fP\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PropertySet\&.SphereCollider\&.SphereCollider (float scale)"

.PP
Initializes a new instance of the \fBSphereCollider\fP class\&. 
.SH "Property Documentation"
.PP 
.SS "float PropertySet\&.SphereCollider\&.Scale\fC [get]\fP"

.PP
The scale of the \fBSphereCollider\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SimulatorAPI from the source code\&.
