[build-system]
requires = ["protobuf", "black", "pyminifier"]

[tool.black]
line-length = 90
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
(
  /(
    \.git
    | \.venv
    | build
    | docs
    | logs
    | proto
    | .vscode
    | dist
    | src/proto_out
  )/
)
'''