.PHONY: all FusionExporter CodeSimulation APS PracticeMode Utilities

all: FusionExporter CodeSimulation APS PracticeMode Utilities

OUTPUT_DIRECTORY := ./out/

FusionExporter:
	claat export -o $(OUTPUT_DIRECTORY) FusionExporter.md

CodeSimulation:
	claat export -o $(OUTPUT_DIRECTORY) CodeSimulation.md

APS:
	claat export -o $(OUTPUT_DIRECTORY) APS.md

PracticeMode:
	claat export -o $(OUTPUT_DIRECTORY) PracticeMode.md

Utilities:
	claat export -o $(OUTPUT_DIRECTORY) Utilities.md
