.PHONY: all FusionExporter CodeSimulation ConfigMode PracticeMode MatchMode ReplayMode Utilities

all: FusionExporter CodeSimulation ConfigMode PracticeMode MatchMode ReplayMode Utilities

FusionExporter:
	claat export -o ./ FusionExporter.md

CodeSimulation:
	claat export -o ./ CodeSimulation.md

ConfigMode:
	claat export -o ./ ConfigMode.md

MatchMode:
	claat export -o ./ MatchMode.md

PracticeMode:
	claat export -o ./ PracticeMode.md

ReplayMode:
	claat export -o ./ ReplayMode.md

Utilities:
	claat export -o ./ Utilities.md
