.PHONY: all FusionExporter CodeSimulation

all: FusionExporter CodeSimulation ConfigMode MatchMode

FusionExporter:
	claat export -o ./ FusionExporter.md

CodeSimulation:
	claat export -o ./ CodeSimulation.md

ConfigMode:
	claat export -o ./ ConfigMode.md

MatchMode:
	claat export -o ./ MatchMode.md
