__title__ = 'apper'
__description__ = 'Fusion 360 API for humans'
__url__ = 'https://apper.readthedocs.io'
__version__ = '0.0.5'
__author__ = 'Patrick Rainsberry'
__author_email__ = 'patrick.rainsberry@autodesk.com'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2019 Patrick Rainsberry'