name: "Setup Fission Bun"
runs:
  using: composite
  steps:
    - name: Bun Setup
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ env.BUN_VERSION }}

    - name: Cache Node Dependencies
      uses: actions/cache@v6
      with:
        key: "${{runner.os}}-npm-fission-${{hashFiles('fission/bun.lock')}}"
        path: "fission/node_modules"
        restore-keys: |
          ${{runner.os}}-npm-fission-
          ${{runner.os}}-npm

    - name: Install Dependencies
      shell: bash
      run: bun install --frozen-lockfile
      working-directory: "fission"