# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: joint.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import types_pb2 as types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='joint.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bjoint.proto\x1a\x0btypes.proto\"y\n\x06Joints\x12\x13\n\x04info\x18\x01 \x01(\x0b\x32\x05.Info\x12#\n\x06joints\x18\x02 \x03(\x0b\x32\x13.Joints.JointsEntry\x1a\x35\n\x0bJointsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x15\n\x05value\x18\x02 \x01(\x0b\x32\x06.Joint:\x02\x38\x01\"\xe7\x02\n\x05Joint\x12\r\n\x05Part1\x18\x01 \x01(\t\x12\r\n\x05Part2\x18\x02 \x01(\t\x12\x13\n\x04info\x18\x03 \x01(\x0b\x32\x05.Info\x12\x1c\n\x06origin\x18\x04 \x01(\x0b\x32\x0c.Vector3_f32\x12\x0e\n\x06Offset\x18\x05 \x01(\x01\x12\r\n\x05\x41ngle\x18\x06 \x01(\x01\x12%\n\x0fJointMotionType\x18\x07 \x01(\x0e\x32\x0c.JointMotion\x12\x14\n\x0cMaximumValue\x18\x08 \x01(\x01\x12\x14\n\x0cMinimumValue\x18\t \x01(\x01\x12\x11\n\tRestValue\x18\n \x01(\x01\x12*\n\x0eRevoluteMotion\x18\x0b \x01(\x0b\x32\x10.RotationalJointH\x00\x12#\n\x0bSlideMotion\x18\x0c \x01(\x0b\x32\x0c.SliderJointH\x00\x12\"\n\x0bRigidMotion\x18\r \x01(\x0b\x32\x0b.RigidJointH\x00\x42\x13\n\x11MotionDescription\"\x8a\x01\n\x0fRotationalJoint\x12\x1b\n\x0cRotationAxis\x18\x01 \x01(\x0e\x32\x05.Axis\x12 \n\nAxisVector\x18\x02 \x01(\x0b\x32\x0c.Vector3_f32\x12\x10\n\x08MaxValue\x18\x03 \x01(\x01\x12\x10\n\x08MinValue\x18\x04 \x01(\x01\x12\x14\n\x0c\x43urrentValue\x18\x05 \x01(\x01\"\x83\x01\n\x0bSliderJoint\x12\x18\n\tSlideAxis\x18\x01 \x01(\x0e\x32\x05.Axis\x12 \n\nAxisVector\x18\x02 \x01(\x0b\x32\x0c.Vector3_f32\x12\x10\n\x08MaxValue\x18\x03 \x01(\x01\x12\x10\n\x08MinValue\x18\x04 \x01(\x01\x12\x14\n\x0c\x43urrentValue\x18\x05 \x01(\x01\"\x0c\n\nRigidJoint\"/\n\nRigidGroup\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0boccurrences\x18\x02 \x03(\t*k\n\x0bJointMotion\x12\t\n\x05Rigid\x10\x00\x12\x0c\n\x08Revolute\x10\x01\x12\n\n\x06Slider\x10\x02\x12\x0f\n\x0b\x43ylindrical\x10\x03\x12\x0b\n\x07PinSlot\x10\x04\x12\n\n\x06Planar\x10\x05\x12\r\n\tBallJoint\x10\x06\x62\x06proto3'
  ,
  dependencies=[types__pb2.DESCRIPTOR,])

_JOINTMOTION = _descriptor.EnumDescriptor(
  name='JointMotion',
  full_name='JointMotion',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Rigid', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Revolute', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Slider', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Cylindrical', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PinSlot', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Planar', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='BallJoint', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=851,
  serialized_end=958,
)
_sym_db.RegisterEnumDescriptor(_JOINTMOTION)

JointMotion = enum_type_wrapper.EnumTypeWrapper(_JOINTMOTION)
Rigid = 0
Revolute = 1
Slider = 2
Cylindrical = 3
PinSlot = 4
Planar = 5
BallJoint = 6



_JOINTS_JOINTSENTRY = _descriptor.Descriptor(
  name='JointsEntry',
  full_name='Joints.JointsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Joints.JointsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='Joints.JointsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=149,
)

_JOINTS = _descriptor.Descriptor(
  name='Joints',
  full_name='Joints',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='Joints.info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='joints', full_name='Joints.joints', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_JOINTS_JOINTSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=149,
)


_JOINT = _descriptor.Descriptor(
  name='Joint',
  full_name='Joint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Part1', full_name='Joint.Part1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Part2', full_name='Joint.Part2', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='info', full_name='Joint.info', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='origin', full_name='Joint.origin', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Offset', full_name='Joint.Offset', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Angle', full_name='Joint.Angle', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='JointMotionType', full_name='Joint.JointMotionType', index=6,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MaximumValue', full_name='Joint.MaximumValue', index=7,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MinimumValue', full_name='Joint.MinimumValue', index=8,
      number=9, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RestValue', full_name='Joint.RestValue', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RevoluteMotion', full_name='Joint.RevoluteMotion', index=10,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SlideMotion', full_name='Joint.SlideMotion', index=11,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='RigidMotion', full_name='Joint.RigidMotion', index=12,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='MotionDescription', full_name='Joint.MotionDescription',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=152,
  serialized_end=511,
)


_ROTATIONALJOINT = _descriptor.Descriptor(
  name='RotationalJoint',
  full_name='RotationalJoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='RotationAxis', full_name='RotationalJoint.RotationAxis', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='AxisVector', full_name='RotationalJoint.AxisVector', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MaxValue', full_name='RotationalJoint.MaxValue', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MinValue', full_name='RotationalJoint.MinValue', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='CurrentValue', full_name='RotationalJoint.CurrentValue', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=514,
  serialized_end=652,
)


_SLIDERJOINT = _descriptor.Descriptor(
  name='SliderJoint',
  full_name='SliderJoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='SlideAxis', full_name='SliderJoint.SlideAxis', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='AxisVector', full_name='SliderJoint.AxisVector', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MaxValue', full_name='SliderJoint.MaxValue', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='MinValue', full_name='SliderJoint.MinValue', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='CurrentValue', full_name='SliderJoint.CurrentValue', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=655,
  serialized_end=786,
)


_RIGIDJOINT = _descriptor.Descriptor(
  name='RigidJoint',
  full_name='RigidJoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=788,
  serialized_end=800,
)


_RIGIDGROUP = _descriptor.Descriptor(
  name='RigidGroup',
  full_name='RigidGroup',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='RigidGroup.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='occurrences', full_name='RigidGroup.occurrences', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=802,
  serialized_end=849,
)

_JOINTS_JOINTSENTRY.fields_by_name['value'].message_type = _JOINT
_JOINTS_JOINTSENTRY.containing_type = _JOINTS
_JOINTS.fields_by_name['info'].message_type = types__pb2._INFO
_JOINTS.fields_by_name['joints'].message_type = _JOINTS_JOINTSENTRY
_JOINT.fields_by_name['info'].message_type = types__pb2._INFO
_JOINT.fields_by_name['origin'].message_type = types__pb2._VECTOR3_F32
_JOINT.fields_by_name['JointMotionType'].enum_type = _JOINTMOTION
_JOINT.fields_by_name['RevoluteMotion'].message_type = _ROTATIONALJOINT
_JOINT.fields_by_name['SlideMotion'].message_type = _SLIDERJOINT
_JOINT.fields_by_name['RigidMotion'].message_type = _RIGIDJOINT
_JOINT.oneofs_by_name['MotionDescription'].fields.append(
  _JOINT.fields_by_name['RevoluteMotion'])
_JOINT.fields_by_name['RevoluteMotion'].containing_oneof = _JOINT.oneofs_by_name['MotionDescription']
_JOINT.oneofs_by_name['MotionDescription'].fields.append(
  _JOINT.fields_by_name['SlideMotion'])
_JOINT.fields_by_name['SlideMotion'].containing_oneof = _JOINT.oneofs_by_name['MotionDescription']
_JOINT.oneofs_by_name['MotionDescription'].fields.append(
  _JOINT.fields_by_name['RigidMotion'])
_JOINT.fields_by_name['RigidMotion'].containing_oneof = _JOINT.oneofs_by_name['MotionDescription']
_ROTATIONALJOINT.fields_by_name['RotationAxis'].enum_type = types__pb2._AXIS
_ROTATIONALJOINT.fields_by_name['AxisVector'].message_type = types__pb2._VECTOR3_F32
_SLIDERJOINT.fields_by_name['SlideAxis'].enum_type = types__pb2._AXIS
_SLIDERJOINT.fields_by_name['AxisVector'].message_type = types__pb2._VECTOR3_F32
DESCRIPTOR.message_types_by_name['Joints'] = _JOINTS
DESCRIPTOR.message_types_by_name['Joint'] = _JOINT
DESCRIPTOR.message_types_by_name['RotationalJoint'] = _ROTATIONALJOINT
DESCRIPTOR.message_types_by_name['SliderJoint'] = _SLIDERJOINT
DESCRIPTOR.message_types_by_name['RigidJoint'] = _RIGIDJOINT
DESCRIPTOR.message_types_by_name['RigidGroup'] = _RIGIDGROUP
DESCRIPTOR.enum_types_by_name['JointMotion'] = _JOINTMOTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Joints = _reflection.GeneratedProtocolMessageType('Joints', (_message.Message,), {

  'JointsEntry' : _reflection.GeneratedProtocolMessageType('JointsEntry', (_message.Message,), {
    'DESCRIPTOR' : _JOINTS_JOINTSENTRY,
    '__module__' : 'joint_pb2'
    # @@protoc_insertion_point(class_scope:Joints.JointsEntry)
    })
  ,
  'DESCRIPTOR' : _JOINTS,
  '__module__' : 'joint_pb2'
  # @@protoc_insertion_point(class_scope:Joints)
  })
_sym_db.RegisterMessage(Joints)
_sym_db.RegisterMessage(Joints.JointsEntry)

Joint = _reflection.GeneratedProtocolMessageType('Joint', (_message.Message,), {
  'DESCRIPTOR' : _JOINT,
  '__module__' : 'joint_pb2'
  # @@protoc_insertion_point(class_scope:Joint)
  })
_sym_db.RegisterMessage(Joint)

RotationalJoint = _reflection.GeneratedProtocolMessageType('RotationalJoint', (_message.Message,), {
  'DESCRIPTOR' : _ROTATIONALJOINT,
  '__module__' : 'joint_pb2'
  # @@protoc_insertion_point(class_scope:RotationalJoint)
  })
_sym_db.RegisterMessage(RotationalJoint)

SliderJoint = _reflection.GeneratedProtocolMessageType('SliderJoint', (_message.Message,), {
  'DESCRIPTOR' : _SLIDERJOINT,
  '__module__' : 'joint_pb2'
  # @@protoc_insertion_point(class_scope:SliderJoint)
  })
_sym_db.RegisterMessage(SliderJoint)

RigidJoint = _reflection.GeneratedProtocolMessageType('RigidJoint', (_message.Message,), {
  'DESCRIPTOR' : _RIGIDJOINT,
  '__module__' : 'joint_pb2'
  # @@protoc_insertion_point(class_scope:RigidJoint)
  })
_sym_db.RegisterMessage(RigidJoint)

RigidGroup = _reflection.GeneratedProtocolMessageType('RigidGroup', (_message.Message,), {
  'DESCRIPTOR' : _RIGIDGROUP,
  '__module__' : 'joint_pb2'
  # @@protoc_insertion_point(class_scope:RigidGroup)
  })
_sym_db.RegisterMessage(RigidGroup)


_JOINTS_JOINTSENTRY._options = None
# @@protoc_insertion_point(module_scope)
