#!/bin/bash

mkdir -p $HOME/.config/Autodesk
if [ -d $HOME/.config/Autodesk/Synthesis ] 
then
rm -rf $HOME/.config/Autodesk/Synthesis 
fi
cp -r /Volumes/Synthesis\ Installer/.Assets/Synthesis $HOME/.config/Autodesk
cp -r /Volumes/Synthesis\ Installer/.Assets/Synthesis.app /Applications
hdiutil detach /Volumes/Synthesis\ Installer -force
exit  
