SkeletalJoint_Base
SkeletalJointFactory SkeletalJoint_Base.JOINT_FACTORY
Factory object used to create skeletal joint objects when reading skeletons from a file.
Referenced by ReadJointFully.
JointDriver SkeletalJoint_Base.cDriver
The joint driver for this joint. This can be null.
Referenced by BXDJSkeleton.WriteSkeleton, BXDJSkeleton.CloneDriversFromTo, RigidNode_Base.GetModelID.
List<RobotSensor> SkeletalJoint_Base.attachedSensors
The sensors that read information from this joint.
Referenced by BXDJSkeleton.WriteSkeleton, BXDJSkeleton.CloneDriversFromTo.
delegate SkeletalJoint_Base SkeletalJoint_Base.SkeletalJointFactory(SkeletalJointType type)
Generic delegate for creating skeletal joints from a joint type.
abstract SkeletalJointType SkeletalJoint_Base.GetJointType()
The type of this joint.
The joint type
Referenced by BXDJSkeleton.WriteSkeleton, BXDJSkeleton.CloneDriversFromTo, JointDriver.GetAllowedDrivers, WriteBinaryJoint, ReadJointFully.
abstract IEnumerable<AngularDOF> SkeletalJoint_Base.GetAngularDOF()
Gets all the angular degrees of freedom for this joint.
The angular degrees of freedom
abstract IEnumerable<LinearDOF> SkeletalJoint_Base.GetLinearDOF()
Gets all the linear degrees of freedom for this joint.
The linear degrees of freedom
void SkeletalJoint_Base.WriteBinaryJoint(System.IO.BinaryWriter writer)
Writes the backing information and ID for this joint to the output stream.
writer Output stream
References GetJointType, JointDriver.WriteBinaryData.
Referenced by ReadJointFully.
void SkeletalJoint_Base.ReadBinaryJoint(System.IO.BinaryReader reader)
Reads the backing information for this joint from the input stream.
reader Input stream
References JointDriver.ReadBinaryData.
Referenced by ReadJointFully.
override string SkeletalJoint_Base.ToString()
void SkeletalJoint_Base.WriteBinaryData(System.IO.BinaryWriter writer)
void SkeletalJoint_Base.ReadBinaryData(System.IO.BinaryReader reader)
abstract void SkeletalJoint_Base.WriteBinaryJointInternal(System.IO.BinaryWriter writer)
abstract void SkeletalJoint_Base.ReadBinaryJointInternal(System.IO.BinaryReader reader)
virtual string SkeletalJoint_Base.ToString_Internal()
static SkeletalJoint_Base SkeletalJoint_Base.ReadJointFully(System.IO.BinaryReader reader)
Identifies the type of a joint, creates an instance, and reads that joint from the given input stream.
reader Input stream The created joint
References JOINT_FACTORY, ReadBinaryJoint, GetJointType, WriteBinaryJoint.
Referenced by BXDJSkeleton.ReadBinarySkeleton.