JointDriver
JointDriverType JointDriver.type
The type of this joint driver.
int JointDriver.portB
float JointDriver.upperLimit
int JointDriver.portA
The port(s) that this joint driver uses.
Referenced by BXDJSkeleton.WriteSkeleton, SetPort.
bool JointDriver.isCan
float JointDriver.lowerLimit
The motion limits for this driver. For continuous rotation this is likely a force or velocity. For linear or limited movement it is motion limits.
Referenced by BXDJSkeleton.WriteSkeleton.
Dictionary<System.Type, JointDriverMeta> JointDriver.MetaInfo
Metadata information for this joint driver.
Referenced by BXDJSkeleton.WriteSkeleton, JointDriver, AddInfo, RemoveInfo< T >, GetInfo< T >, GetInfo, SetLimits, WriteBinaryData, ReadBinaryData.
JointDriver.JointDriver()
Creates as joint driver with no type. This is mainly for IO
References MetaInfo.
JointDriver.JointDriver(JointDriverType type)
Creates a joint driver with the given type.
type Driver type
void JointDriver.AddInfo(JointDriverMeta metaDriver)
Adds the given joint driver metadata object to this driver, or replaces the existing metadata of the same type.
metaDriver The metadata
References MetaInfo.
Referenced by ReadBinaryData.
T JointDriver.RemoveInfo< T >()
Removes the metadata of the given type stored in this joint driver and returns it, or null if no such metadata exists.
T The type of the metadata Metadata, or null
References MetaInfo.
T JointDriver.GetInfo< T >()
Gets the metadata of the given type stored in this joint driver, or null if no such metadata exists.
T The type of the metadata Metadata, or null
References MetaInfo.
JointDriverMeta JointDriver.GetInfo(System.Type type)
Gets the metadata of the given type stored in this joint driver, or null if no such metadata exists.
type The type to get info for Metadata, or null
References MetaInfo.
void JointDriver.CopyMetaInfo(JointDriver toCopy)
void JointDriver.SetPort(int portA, int portB=-1)
Sets the port(s) for this driver.
portA First port portB Option second port
References portA.
void JointDriver.SetLimits(float lower, float upper)
Sets the limits for this driver.
For all linear motion these represent the linear limits on that motion. For all limited angular motion these represent the angular limits on that motion. For all continuous angular motion these represent the force limits on that motion. lower Lower limit upper Upper limit
References GetDriveType, MetaInfo.
override string JointDriver.ToString()
JointDriverType JointDriver.GetDriveType()
Gets the type of this joint driver.
Driver type
Referenced by BXDJSkeleton.WriteSkeleton, SetLimits, WriteBinaryData.
void JointDriver.WriteBinaryData(System.IO.BinaryWriter writer)
Writes the binary representation of this driver to the stream.
writer Output stream
References GetDriveType, MetaInfo.
Referenced by SkeletalJoint_Base.WriteBinaryJoint.
void JointDriver.ReadBinaryData(System.IO.BinaryReader reader)
Reads the binary representation of this driver from the stream.
reader Input stream
References MetaInfo, AddInfo.
Referenced by SkeletalJoint_Base.ReadBinaryJoint.
int JointDriver.CompareTo(JointDriver driver)
static JointDriverType [] JointDriver.GetAllowedDrivers(SkeletalJoint_Base joint)
Gets the possible types of joint drivers for the given skeletal joint.
joint Skeletal joint to get allowed types for Joint driver options
References SkeletalJoint_Base.GetJointType.