RigidNode_Base
RigidNodeFactory RigidNode_Base.NODE_FACTORY
By setting this to a custom value skeletons that are read using BXDJSkeleton.ReadBinarySkeleton(string) can be composed of a custom rigid node type.
int RigidNode_Base.level
How far down in the hierarchy this element is. The higher it is the farther from the root node.
Referenced by AddChild.
RigidNode_Base RigidNode_Base.parent
The node that represents the parent of this node. If this is null then this is a root node.
SkeletalJoint_Base RigidNode_Base.parentConnection
The joint that connects this node to its parent.
string RigidNode_Base.ModelFileName
The name of the file holding this node's model.
Referenced by BXDJSkeleton.ReadBinarySkeleton.
string RigidNode_Base.ModelFullID
A very verbose identifier that represents the element this node is in the overall structure.
Referenced by BXDJSkeleton.ReadBinarySkeleton, GetModelID.
Dictionary<SkeletalJoint_Base, RigidNode_Base> RigidNode_Base.Children
A mapping between each child node of this node and the joint connection between the two.
Guid RigidNode_Base.GUID
The globally unique identifier.
Referenced by RigidNode_Base.
delegate RigidNode_Base RigidNode_Base.RigidNodeFactory(Guid guid)
Generic delegate for creating rigid node instances
RigidNode_Base.RigidNode_Base(Guid guid)
Initializes a new instance of the RigidNode_Base class.
guid
References GUID.
void RigidNode_Base.AddChild(SkeletalJoint_Base joint, RigidNode_Base child)
Adds the given node as a child of this node.
joint The joint connecting this node to the child child The child node
References level.
Referenced by BXDJSkeleton.ReadBinarySkeleton.
RigidNode_Base RigidNode_Base.GetParent()
Gets the parent node for this node.
The parent node, or null if this node is a root node
SkeletalJoint_Base RigidNode_Base.GetSkeletalJoint()
Gets the skeletal joint connecting this node to its parent.
This should always be non-null when the current node isn't a root node. The joint connection, or null if no connection exists.
Referenced by BXDJSkeleton.CloneDriversFromTo.
virtual object RigidNode_Base.GetModel()
Gets the actual object visually representing this rigid node if such an item exists.
The representation, or null
virtual string RigidNode_Base.GetModelID()
Gets a very verbose identifier that represents the element this node is in the overall structure.
The model identifier
References ModelFullID, SkeletalJoint_Base.cDriver.
Referenced by BXDJSkeleton.CloneDriversFromTo.
override string RigidNode_Base.ToString()
List<RigidNode_Base> RigidNode_Base.ListAllNodes()
Gets a list of all the rigid nodes at or below this item in the tree.
The list of nodes
Referenced by BXDJSkeleton.SetupFileNames, BXDJSkeleton.WriteSkeleton, BXDJSkeleton.CloneDriversFromTo.
void RigidNode_Base.ListAllNodes(List< RigidNode_Base > list)
Gets a list of all the rigid nodes at or below this item in the tree.
list The list to write the nodes to