FieldNodeGroup
string FieldNodeGroup.NodeGroupID
The string ID for the FieldNodeGroup.
Referenced by BXDFProperties.WriteProperties, AddNodeGroup.
Dictionary<string, FieldNode> FieldNodeGroup.childNodes
A list containing each child FieldNode.
Dictionary<string, FieldNodeGroup> FieldNodeGroup.childNodeGroups
A list containing each child FieldNodeGroup.
FieldNode FieldNodeGroup.this[string path]
Used for setting or getting a FieldNode from the path supplied.
path
delegate FieldNode FieldNodeGroup.HandleChildInfo(string childName, string childPath, bool lastChild)
Used for defining how a child will be processed while iterating through a node path.
childName childPath lastChild
FieldNode FieldNodeGroup.ProcessNextChild(string path, HandleChildInfo Handle)
Used for processing the next child in a path string.
path Handle
FieldNodeGroup.FieldNodeGroup(string nodeGroupID)
Constructs a new instance of the FieldNodeGroup class.
nodeGroupID
Referenced by AddNodeGroup.
FieldNode FieldNodeGroup.AddNode(string nodeID, string physicsGroupID=BXDFProperties.BXDF_DEFAULT_NAME)
Adds a new node with the given ID and physicsGroupID to the childNodes Dictionary.
nodeID
void FieldNodeGroup.AddNode(FieldNode node)
Adds the given FieldNode to the ChildNodes Dictionary.
node
References FieldNode.NodeID.
FieldNode FieldNodeGroup.GetNode(string nodeID)
Returns the child FieldNode with the given nodeID.
nodeID The FieldNode.
FieldNodeGroup FieldNodeGroup.AddNodeGroup(string nodeGroupID)
Adds a new FieldNodeGroup with the given ID.
nodeGroupID
References FieldNodeGroup.
void FieldNodeGroup.AddNodeGroup(FieldNodeGroup nodeGroup)
Adds the given FieldNodeGroup to the childNodeGroups Dictionary.
nodeGroup
References NodeGroupID.
FieldNodeGroup FieldNodeGroup.GetNodeGroup(string nodeGroupID)
Returns the FieldNodeGroup with the given nodeGroupID.
nodeGroupID The FieldNodeGroup.
IEnumerable<FieldNode> FieldNodeGroup.EnumerateFieldNodes()
Enumerates through all direct child FieldNodes.
Referenced by BXDFProperties.WriteProperties, EnumerateAllLeafFieldNodes.
IEnumerable<FieldNodeGroup> FieldNodeGroup.EnumerateFieldNodeGroups()
Enumerates through all direct child FieldNodeGroups.
Referenced by BXDFProperties.WriteProperties, EnumerateAllLeafFieldNodes.
IEnumerable<FieldNode> FieldNodeGroup.EnumerateAllLeafFieldNodes()
Enumerates through each child FieldNode in all child FieldNodeGroups.
References EnumerateFieldNodes, EnumerateFieldNodeGroups, EnumerateAllLeafFieldNodes.
Referenced by EnumerateAllLeafFieldNodes.