// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoomInfo } from "./RoomInfo"

export type ServerToClientMessage =
    | { type: "kick"; client_id: string }
    | { type: "roomlist"; rooms: Array<RoomInfo> }
    | { type: "sendinfo"; room_id: string; client_id: string }
    | { type: "pong"; client_send_ts: number; server_ts: number }
