#!/bin/bash

APP_DIRECTORY=$HOME/"Library"

INSTALL_DIR=${APP_DIRECTORY}/"Application Support"/${PRODUCT}/${VERSION}

APPLICATION_FILE_PATH=${INSTALL_DIR}/Contents/MacOS/

echo "Post installation process started"

#Change permissions in home directory
echo "Change permissions in product home"
cd ${INSTALL_DIR}
chmod -R 755 .
[ -d /usr/local/bin ] || mkdir /usr/local/bin

#Add application shortcut to /usr/local/bin
rm -f /usr/local/bin/__PRODUCT__-__VERSION__
ln -s ${APPLICATION_FILE_PATH} /usr/local/bin/__PRODUCT__-__VERSION__
echo "Post installation process finished"
