name: Fusion - Black Format Validation

on:
  workflow_dispatch: {}
  push:
    branches: [ prod, dev ]
  pull_request:
    branches: [ prod, dev ]

jobs:
  blackFormatChecker:
    name: Black Format Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      - name: Python Setup
        uses: actions/setup-python@v7
        with:
          python-version: '3.10'
      - name: Setup Dependencies
        run: python3 -m pip install -r ./exporter/SynthesisFusionAddin/requirements-dev.txt
      - name: Validate Isort Formatting
        run: python3 ./exporter/SynthesisFusionAddin/tools/verifyIsortFormatting.py
      - name: Validate Black Formatting
        run: python3 -m black --check --config ./exporter/SynthesisFusionAddin/pyproject.toml ./exporter/SynthesisFusionAddin/
