name: Format Validation (Clang)

on:
  workflow_dispatch: {}
  push: {}
  pull_request:
    branches: [ master, dev ]

jobs:
  runFormatValidationScript:
    name: Run Clang Format Validation Script
    runs-on: ubuntu-latest
    steps:
    - name: Get Clang Format
      run: |
        if [[ ! -f /etc/apt/trusted.gpg.d/apt.llvm.org.asc ]]; then
            sudo wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
        fi

        sudo add-apt-repository "deb http://apt.llvm.org/jammy/  llvm-toolchain-jammy-16 main"
        sudo apt-get update
        sudo apt-get install -y clang-format-16
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Python Setup
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Run Script
      run: python3 scripts/format/format_validation.py
      id: format-validation
      continue-on-error: true
    - name: Check Success
      run: |
        if [ ${{ steps.format-validation.outcome }} == "success" ]; then
          echo "Format Validation Passed"
        else
          echo "Format Validation Failed"
          exit 1
        fi
