name: Engine

on:
  workflow_dispatch: {}
  push: { branches: [master] }

jobs:
  buildForSomePlatforms:
    name: Build for ${{ matrix.targetPlatform }} on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - engine/
        unityVersion:
          - 2022.3.2f1
        targetPlatform:
          - StandaloneWindows64
          - StandaloneLinux64
          - StandaloneOSX
    steps:
      - name: Checkout Repository & Submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/cache@v1.1.0
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-
            Library-
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
        with:
          version: "23.3"
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Setup Dependencies
        run: |
          bash ./init.sh
          bash ./init.sh
      - name: Build Unity
        uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: ${{ matrix.projectPath }}
          allowDirtyBuild: true
      - uses: actions/upload-artifact@v1
        with:
          name: Synthesis-${{ matrix.targetPlatform }}
          path: build
