name: Exporter Formatter

on:
  workflow_dispatch: {}
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  blackFormatChecker:
    name: Black Formatter for Python Exporter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rickstaa/action-black@v1
        with:
          black_args: "./exporter/SynthesisFusionAddin/ --check"
