name: Fission - Package

on:
  workflow_dispatch: {}
  push:
    branches: [prod, dev]

jobs:
  runUnitTests:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup Fission Bun
        uses: ./.github/actions/FissionSetup

      - name: Get date
        id: date # this is used on variable path
        run: |
          echo "timestamp=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_OUTPUT

      

      - name: Get package info
        id: info
        uses: codex-team/action-nodejs-package-info@v1.1
        with:
          path: fission/

      - name: Build
        id: build
        working-directory: "fission"
        run: |
          bun run build:prod
          bun run build:dev

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        id: upload-artifact-prod
        with:
          name: "${{ steps.info.outputs.name }}@${{ steps.info.outputs.version }}[${{ steps.date.outputs.timestamp }}]"
          path: fission/dist/prod/

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        id: upload-artifact-dev
        with:
          name: "${{ steps.info.outputs.name }}-dev@${{ steps.info.outputs.version }}[${{ steps.date.outputs.timestamp }}]"
          path: fission/dist/dev/
