name: Fission - Build

on:
  workflow_dispatch: {}
  pull_request:
    branches: [prod, dev]

jobs:
  buildFission:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/FissionSetup

      - name: Build Fission
        working-directory: "fission"
        run: bun run build && echo "Build Passed" || (echo "Build Failed" && exit 1)
