name: Fission

on:
  workflow_dispatch: {}
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  runUnitTests:
    name: Package
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: JavaScript Setup
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Install Dependencies
      run: |
        cd fission
        npm install

    - name: Get package info
      id: info
      uses: codex-team/action-nodejs-package-info@v1.1

    - name: Build
      id: build
      run: |
        cd fission
        npm run build

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      id: upload-artifact
      with:
        name: "${{ steps.info.outputs.name }}@${{ steps.info.outputs.version }} [$(date +'%Y-%m-%dT%H:%M:%S')]"
        path: "dist"