name: Fission - ES Lint Format Validation

on:
  workflow_dispatch: {}
  push: 
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  runFormatValidationScript:
    name: ESLint Format Validation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: JavaScript Setup
      uses: actions/setup-node@v2
      with:
        node-version: 20
    - name: Install Dependencies
      run: |
        cd fission
        npm install
    - name: Linter
      id: linter-validation
      run: |
        cd fission
        npm run lint && echo "ESLint Validation Passed" || (echo "ESLint Validation Failed" && exit 1)
      continue-on-error: true
    - name: Prettier
      id: prettier-validation
      run: |
        cd fission
        npx prettier --version
        npm run prettier && echo "Prettier Validation Passed" || (echo "Prettier Validation Failed" && exit 1)
      continue-on-error: true
