name: Fission - ES Lint Format Validation

on:
  workflow_dispatch: {}
  push: 
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  runFormatValidationScript:
    name: ESLint Format Validation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: JavaScript Setup
      uses: actions/setup-node@v2
      with:
        node-version: 20
    - name: Install Dependencies
      run: |
        cd fission
        npm install
    - name: Linter
      id: linter-validation
      run: |
        cd fission
        npm run lint
      continue-on-error: true
    - name: Check EsLint
      run: |
        if [ ${{ steps.linter-validation.outcome }} == "success" ]; then
          echo "EsLint Validation Passed"
        else
          echo "EsLint Validation Failed"
          exit 1
        fi
      continue-on-error: true
    - name: Prettier
      id: prettier-validation
      run: |
        cd fission
        npm run prettier
      continue-on-error: true
    - name: Check Prettier
      run: |
        if [ ${{ steps.prettier-validation.outcome }} == "success" ]; then
          echo "Prettier Validation Passed"
        else
          echo "Prettier Validation Failed"
          exit 1
        fi
