name: Fission - Unit Test

on:
  workflow_dispatch: {}
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  runUnitTests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: JavaScript Setup
      uses: actions/setup-node@v2
      with:
        node-version: 20
    - name: Install Dependencies
      run: |
        cd fission
        npm install
        npm install -g run-script-os
        npm run assetpack
        npx playwright install
    - name: Unit Tests
      id: unit-tests
      run: |
        cd fission
        npm run test
        npm run test:firefox
      continue-on-error: true
    - name: Check Success
      run: |
        if [ ${{ steps.unit-tests.outcome }} == "success" ]; then
          echo "Format Validation Passed"
        else
          echo "Format Validation Failed"
          exit 1
        fi