name: Fission - Build

on:
  workflow_dispatch: {}
  pull_request:
    branches: [master, dev]

jobs:
  runUnitTests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: JavaScript Setup
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          cd fission
          npm install

      - name: Build Fission
        run: |
          cd fission
          npm run build && echo "Build Passed" || (echo "Build Failed" && exit 1)
