name: Fusion - mypy Typing Validation

on:
  workflow_dispatch: {}
  push:
    branches: [ prod, dev ]
  pull_request:
    branches: [ prod, dev ]

jobs:
  mypy:
    name: Run mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install mypy
      - name: Test mypy
        working-directory: ./exporter/SynthesisFusionAddin
        run: |
          mypy --install-types
          mypy
