name: Fusion - mypy Typing Validation

on:
  workflow_dispatch: {}
  push:
    branches: [ prod, dev ]
  pull_request:
    branches: [ prod, dev ]

jobs:
  mypy:
    strategy:
      matrix:
        target: [
          "exporter/SynthesisFusionAddin",
        ]
    name: Run mypy on ${{ matrix.target }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install mypy
      - run: mypy --config-file ${{ matrix.target }}/mypy.ini
