name: Fusion - WebUI Build and Format

on:
  workflow_dispatch: {}

  push: 
    branches: [ prod, dev ]
    paths:
      - 'exporter/SynthesisFusionAddin/web/**'
  pull_request:
    branches: [ prod, dev ]
    paths:
      - 'exporter/SynthesisFusionAddin/web/**'


jobs:
  runFormatValidationScript:
    name: ESLint Format Validation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: JavaScript Setup
      uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: Cache Node Dependencies
      uses: actions/cache@v3
      with:
        key: "${{runner.os}}-npm-fusion-${{hashFiles('exporter/SynthesisFusionAddin/web/package-lock.json')}}"
        path: 'exporter/SynthesisFusionAddin/web/node_modules'
        restore-keys: |
          ${{runner.os}}-npm-fusion-
          ${{runner.os}}-npm

    - name: Install Dependencies
      run: |
        cd exporter/SynthesisFusionAddin/web
        npm ci

    - name: Linter
      id: linter-validation
      if: ${{ always() }}
      run: |
        cd exporter/SynthesisFusionAddin/web
        npm run lint && echo "ESLint Validation Passed" || (echo "ESLint Validation Failed" && exit 1)

    - name: Prettier
      id: prettier-validation
      if: ${{ always() }}
      run: |
        cd exporter/SynthesisFusionAddin/web
        npx prettier --version
        npm run prettier && echo "Prettier Validation Passed" || (echo "Prettier Validation Failed" && exit 1)
  runBuildScript:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: JavaScript Setup
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Cache Node Dependencies
        uses: actions/cache@v3
        with:
          key: "${{runner.os}}-npm-fusion-${{hashFiles('exporter/SynthesisFusionAddin/web/package-lock.json')}}"
          path: 'exporter/SynthesisFusionAddin/web/node_modules'
          restore-keys: |
            ${{runner.os}}-npm-fusion-
            ${{runner.os}}-npm

      - name: Install Dependencies
        run: |
          cd exporter/SynthesisFusionAddin/web
          npm ci

      - name: Build
        id: build
        if: ${{ always() }}
        run: |
          cd exporter/SynthesisFusionAddin/web
          npm run build && echo "Build Successful" || (echo "Build Failed" && exit 1)