name: Fusion - mypy Typing Validation

on:
  workflow_dispatch: {}
  push:
    branches: [ prod, dev ]
  pull_request:
    branches: [ prod, dev ]

jobs:
  mypy:
    name: Run mypy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./exporter/SynthesisFusionAddin
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements-mypy.txt
      - run: mypy
