name: Glueball - Build
on:
  release:
    types:
      - created
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read
  attestations: write

jobs:
  releaseBuildGlueball:
    name: Glueball Release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin

          - build: windows-gnu
            os: windows-latest
            target: x86_64-pc-windows-gnu
    defaults:
      run:
        working-directory: "glueball"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: ${{ matrix.target }}
      - name: Build server
        id: build
        shell: bash
        run: |
          mkdir build
          cargo build --release --target ${{ matrix.target }} --verbose --target-dir ./build
          echo "file=$(echo ./build/*)" >> "$GITHUB_OUTPUT

      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-path: ${{ steps.build.output.file }}

      - name: Upload Release Asset
        if: github.ref_type == 'tag'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh release upload ${{ github.event.release.tag_name }}  ${{ steps.build.output.file }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        if: github.ref_type != 'tag'
        with:
          path: ${{ steps.build.output.file }}
          archive: false


