---
name: Nix Flake - Check

on:
  workflow_dispatch: {}
  push:
    branches: [ prod, dev ]
  pull_request:
    branches: [ prod, dev ]

jobs:
  flake-check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31

      - run: nix flake check

  formatting-check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6

      - uses: cachix/install-nix-action@v31

      - run: nix fmt -- --ci
