name: Test Nix

on:
  push:
  pull_request:

jobs:
  nix-flake-check:
    name: Nix Flake Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: cachix/install-nix-action@v31

      - name: Nix Flake Check
        run: nix flake check

  fission-playwright:
    name: Fission Playwright
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: cachix/install-nix-action@v31

      - name: Cache Node Dependencies
        uses: actions/cache@v6
        with:
          key: "${{runner.os}}-npm-fission-${{hashFiles('fission/bun.lock')}}"
          path: "fission/node_modules"
          restore-keys: |
            ${{runner.os}}-npm-fission-
            ${{runner.os}}-npm

      - name: Install Dependencies
        working-directory: "fission"
        run: nix develop .#fission --command bun -c "install --frozen-lockfile"
      
      - name: Run Playwright Tests
        working-directory: "fission"
        run: |
          nix develop .#fission --command bun -c "run test run ./src/test/APSTesting.test.ts"
