# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Slack PR notification
on:
  pull_request:
    types:
      - opened
      - reopened
      - closed

jobs:
  notify:
    name: Send Slack notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Send Slack notification
        run: bun .github/workflows/slack/pr_opened.ts
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_DATA: ${{ toJSON(github) }}