# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Slack PR review notification
on:
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed
  issue_comment:
    types:
      - created
  pull_request_review_comment:
    types:
      - created

jobs:
  notify:
    name: Send Slack notification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Send Slack notification
        run: bun .github/workflows/slack/pr_review.ts
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GITHUB_DATA: ${{ toJSON(github) }}
